# GENERAL Settings:
run.time.seconds=6000000
tw.download.enabled=true
sq.cdf.update.enabled=false
tw.observe.enabled=false
sq.trade.enabled=false


# TW DOWNLOAD MODE Settings:
tw.download.check.interval.seconds=10
tw.download.interval.minutes=1
tw.download.timeframe.minutes=600
tw.download.timeframe.wait.to.load.seconds=10


# SQ SYNC CDF MODE Settings:
cdf.update.interval.seconds=10


# TW OBSERVE MODE Settings:
tw.update.interval.milli=0


# SQ OBSERVE MODE Settings:
sq.update.interval.milli=1000


# SQ TRADE MODE Settings:









# PATHS (relative to HOME)
quotes.dir.tmp=/docs/abricore/quotes/tmp/
quotes.dir.store=/docs/abricore/quotes/store/
quotes.dir.processed=/docs/abricore/quotes/processed/
strat.dir.store=/docs/abricore/strategies/
logs.dir=/docs/abricore.logs/
