run.time.seconds=6000000
tw.update.interval.milli=0
tw.download.check.interval.seconds=60
tw.download.interval.minutes=60
tw.download.timeframe.minutes= 600
cdf.update.interval.seconds=600

# PATHS (relative to HOME)
quotes.dir.tmp=/docs/abricore/quotes/tmp/
quotes.dir.store=/docs/abricore/quotes/store/
quotes.dir.processed=/docs/abricore/quotes/processed/
strat.dir.store=/docs/abricore/strategies/
logs.dir=/docs/abricore.logs/
